apiVersion: v1 
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv-a
  spec:
    capacity:
      storage: 1Mi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    # gcePersistentDisk:
    #   pdName: pv-a
    #   fsType: nfs4
    hostPath:
      path: "/mnt/data2"

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv-b
  spec:
    capacity:
      storage: 1Mi
    accessModes:
      - ReadWriteOnce
    # persistentVolumeReclaimPolicy: Recycle
    # gcePersistentDisk:
    #   pdName: pv-b
    #   fsType: nfs4
    hostPath:
      path: "/mnt/data1"
      
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv-c
  spec:
    capacity:
      storage: 1Mi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    # gcePersistentDisk:
    #   pdName: pv-c
    #   fsType: nfs4
    hostPath:
      path: "/mnt/data"