apiVersion: v1 
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pv-a
  spec:
    capacity:
      storage: 1Mi
    accessModes:
      - ReadWriteOnce
    PersistentVolumeReclaimPolicy: Recycle
    gcePersistentDisk:
      pdNamee: pv-a
      fsType: nfs4

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pv-b
  spec:
    capacity:
      storage: 1Mi
    accessModes:
      - ReadWriteOnce
    PersistentVolumeReclaimPolicy: Recycle
    gcePersistentDisk:
      pdNamee: pv-b
      fsType: nfs4
      
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pv-c
  spec:
    capacity:
      storage: 1Mi
    accessModes:
      - ReadWriteOnce
    PersistentVolumeReclaimPolicy: Recycle
    gcePersistentDisk:
      pdNamee: pv-c
      fsType: nfs4
